version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: springbatch
      POSTGRES_PASSWORD: springbatch
      POSTGRES_DB: batchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
